SYSTEM:
  NUM_WORKERS: 8
TRAIN:
  IMG_SIZE: 473
  BENCHMARK: pascal
  BSZ: 16
  LR: 5e-4
  DECODER_LR: 5e-4
  LR_SCHEDULER: constant
  NITER: 300
  FOLD: 2
  BACKBONE: resnet101
  CATS_AUGMENTATIONS: True
  PFENET_AUGMENTATIONS: False
  MASK: True
  WEIGHT_DECAY: 0.0
  DECODER_WEIGHT_DECAY: 0.0
  MILESTONES: